### ISSUE TITLE
Error when iterating over a never-watched show

### ISSUE THREAD

**Issue by alexthemaster** [SIMKL/Sync-Simkl-to-Plex-Chrome-Extension#10]
Just like the title says, it seems that when the script attempts to loop through the a season of a Simkl show that you never marked any episode as played it will error. (Breaking Bad is in my plan to watch list)

![image](https://user-images.githubusercontent.com/31011461/156897744-f09af174-ad22-4cf6-9a3e-da832145036f.png)

[This](https://github.com/SIMKL/Sync-Simkl-to-Plex-Chrome-Extension/blob/71b4d6fd52a4adee3cd64aca1e6cbf46fdf8bba6/src/js/background/sync.js#L597-L608) is the forEach loop in question.

**Comment by phanirithvij** [comment]
thanks again. fixed

**Comment by phanirithvij** [comment]
I overwrote the v0.0.2 release. you can test after downloading it again.
