### ISSUE TITLE
Errors while loading (JS file missing)

### ISSUE THREAD

**Issue by alexthemaster** [SIMKL/Sync-Simkl-to-Plex-Chrome-Extension#8]
The extension gives out three errors the moment you load it. Here they are:
![image](https://user-images.githubusercontent.com/31011461/156896528-ec90cb43-f0bf-44f5-9140-abfe09dd2a5c.png)
![image](https://user-images.githubusercontent.com/31011461/156896533-f5e95e47-2559-4e2b-a221-be9f375f943d.png)
![image](https://user-images.githubusercontent.com/31011461/156896539-c16159de-e6ed-4f87-955b-8c9b22945c4c.png)

Seems like a simple issue to fix.

Tested on Vivaldi and Chrome (both on latest version)

EDIT: After taking a quick look at the source files I noticed that there in fact isn't any env javascript file present

**Comment by phanirithvij** [comment]
Oh yeah sorry about that, download the zip instead of cloning for now.

**Comment by alexthemaster** [comment]
While the ZIP file from the releases tab does indeed have the env file present, it however doesn't have a Simkl application client ID and secret. Is the user supposed to create an application to use this extension or was it a mistake?

**Comment by phanirithvij** [comment]
Thanks for reporting that, @masyk please add repository secrets for them.

**Comment by phanirithvij** [comment]
@alexthemaster you can try with the v0.0.2 one I tested it locally now it works, I forgot to ask masyk to add repo secrets before as I had them added in my fork thus I didn't realise.
